### ISSUE TITLE
Cursor position calculation wrong in Chrome 71 and Firefox 63

### ISSUE THREAD

**Issue by nununoisy** [jsdf/little-virtual-computer#4]
The cursor position and mouse pixel are wrong in Chrome 71 and Firefox 63. This issue is reproducible by running the paint program:
+ Pixels draw in the wrong place
+ It's impossible to switch colors
+ Moving to the bottom causes an invalid memory write and halts the computer

Inspecting the cursor x/y values (slots 2010/2011), it seems that x is 6 too low and y is 6 too high. Could this also impact the mouse pixel value (slot 2012)?

Edit: add Firefox

**Comment by nununoisy** [comment]
Please take a look at the PR at #6.

**Comment by alexanderbrown21** [comment]
HI @nununoisy  I've also experienced this in both browsers(at the version you specified) and Opera 57.0.3098.116 (Windows 10 64bit) also has this issue as well.  Running this in edge(42.17134.1.0) returns blurred pixels as shown below. 
![image](https://user-images.githubusercontent.com/4406173/51446599-5090f100-1d0c-11e9-8c6c-d73a3fd60754.png)

**Comment by nununoisy** [comment]
@alexanderbrown21 Thank you for the response and verification! The blurry pixels in Edge is a weird error (but then again it's Microsoft...). Would you be willing to verify that my PR works using my fork's [GitHub Pages link](https://nununoisy.github.io/little-virtual-computer/computer1)?

**Comment by alexanderbrown21** [comment]
Yes I will be gladly help to confirm this i will let you know when I have.

**Comment by alexanderbrown21** [comment]
HI @nununoisy  I can let you know that it works when you first load the page "maximized" it appears to work fine in both browser at the version tested.

However resizing the browser window will result in the same issue as before if the window is small:
- Pixels draw in the wrong place
- It's impossible to switch colors.

Chrome and Firefox appears to work fine with the paint program until under half(or little over half) of the screen is taken up by the browser horizontally(at least on a 20 inch monitor). However, the paint program appear to work fine again if you then resize the window back to size it likes or maximise the window. 

Starting the browser in restored state, when window is small as you expect will  draw in the wrong place again, and resize the window again to a size it likes will mean selecting colours in the pallette will be out of line. e.g. select pink but green is on the paint window, select yellow but pink is on the paint window.

Hope this make sense.

**Comment by nununoisy** [comment]
Thanks so much! I'll go ahead and do some debugging later today and see if I can fix the cursor detection code.

**Comment by alexanderbrown21** [comment]
It looks like the pallette moves from  above the black box of the "computer", a click on random place above it an it showed a different colour.

**Comment by alexanderbrown21** [comment]
how is it going with this?

**Comment by jsdf** [comment]
Hi, I haven't been looking at Github for a while, but I'm back now, so I'll take a look at this soon

**Comment by jsdf** [comment]
fixed in https://github.com/jsdf/little-virtual-computer/commit/3b58750983f24a7fe26743e58fc495562cae652f

**Comment by alexanderbrown21** [comment]
Hey sorry didn't get back to you I hope to see if that works, let you know if I find an issue.
